### ISSUE TITLE
usb/network communication using NS_BL1U

### ISSUE THREAD

**Issue by dhimanchakraborty** [96boards-hikey/atf-fastboot#2]
Is it possible to have usb and network communication at the bootloader level(bl1, bl2, bl2u or bl3*)?
Which bootloader is good for usb and network communication?

So technically I can use NS_BL1U to perform usb/network communication if I can able to play with the payload. Am I correct here?

Is there any NS_BL1U implementation available for hikey boards other than this one?
Can it be used with normal ATF-UEFI-build [found here](https://github.com/96boards-hikey/tools-images-hikey960/blob/master/build-from-source/README-ATF-UEFI-build-from-source.md) for hikey960? If board is an issue I have a hikey620 handy also.

**Comment by vchong** [comment]
As replied in https://discuss.96boards.org/t/usb-and-network-support-at-bootloader/3391/8

**Comment by dhimanchakraborty** [comment]
@vchong Thanks for the reply. Much appreciated. 
I think we should continue at 96boards forum for further communication.
